# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets/dropdown_arrow.svg', 'assets'),
        ('assets/app_icon.ico', 'assets'),
    ],
    hiddenimports=[
        'PyQt6.QtSerialPort',
        'PyQt6.QtSvg',
        'bleak',
        'bleak.backends.winrt',
        'winrt.windows.applicationmodel',
        'winrt.windows.applicationmodel.activation',
        'winrt.windows.applicationmodel.background',
        'winrt.windows.applicationmodel.core',
        'winrt.windows.devices.bluetooth',
        'winrt.windows.devices.bluetooth.advertisement',
        'winrt.windows.devices.bluetooth.genericattributeprofile',
        'winrt.windows.devices.bluetooth.rfcomm',
        'winrt.windows.devices.enumeration',
        'winrt.windows.devices.radios',
        'winrt.windows.foundation',
        'winrt.windows.foundation.collections',
        'winrt.windows.networking',
        'winrt.windows.networking.connectivity',
        'winrt.windows.networking.sockets',
        'winrt.windows.security.credentials',
        'winrt.windows.storage',
        'winrt.windows.storage.search',
        'winrt.windows.storage.streams',
        'winrt.windows.system',
        'winrt.windows.system.diagnostics',
        'winrt.windows.system.remotesystems',
        'winrt.windows.ui',
        'winrt.windows.ui.popups',
        'winrt.windows.ui.viewmanagement',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='DataReceiveAndAnalysis',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/app_icon.ico',
)
